language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
sudo: false
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
    email:
        recipients:
            - jmitchell38488@gmail.com

script: "npm test"
after_success: "npm run nyc-coverage"
